services:
  - type: web
    name: ewaste-management
    env: python
    region: singapore
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn index:app"
    envVars:
      - key: FLASK_ENV
        value: production
